#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5
picom -b
~/.config/polybar/launch.sh
setxkbmap -option grp:alt_shift_toggle -layout us,ru
xsetroot -cursor_name left_ptr
~/.fehbg
dunst &

bspc config border_width         	2
bspc config window_gap           	4 

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer true
bspc config border_radius         6
bspc config normal_border_color  	"#3c3836"
bspc config focused_border_color 	"#a89984"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
